'$schema' = 'https://starship.rs/config-schema.json'
add_newline = false

[aws]
symbol = "îŒ½  " # TODO

[buf]
symbol = "ï’ " # TODO

[c]
symbol = "í€© "

[character]
vicmd_symbol = '[î˜«](bold green)'
vimcmd_replace_one_symbol = '[r](bold red)'
vimcmd_replace_symbol = '[R](bold red)'
vimcmd_visual_symbol = '[V](bold purple)'

[cmd_duration]
disabled = true

[conda]
symbol = "ï„Œ " # TODO

[dart]
symbol = "í "

[directory]
read_only = " í‚·"

[docker_context]
symbol = "í— "

[elixir]
symbol = "í  "

[elm]
symbol = "í¡ "

[git_status]
stashed = ""

[git_branch]
symbol = "í¸ "

[golang]
symbol = 'í½ '

[guix_shell]
symbol = "ïŒ¥ " # TODO

[haskell]
symbol = "í‚Œ "

[haxe]
symbol = "í‚ "

[hg_branch]
symbol = "í¸ "

[java]
disabled = true
symbol = "í‚ "

[lua]
symbol = 'í‚º '

[julia]
symbol = "í‚¦ "

[memory_usage]
symbol = "ï¡š " # TODO

[meson]
symbol = "íƒ‚ "

[nim]
symbol = "íƒ‘ "

[nix_shell]
symbol = "íƒ’ "

[nodejs]
disabled = true
symbol = "íƒ“ "

# TODO
[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
openSUSE = "ïŒ” "
OracleLinux = "ï ¶ "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ï´± "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï¡± "

[package]
symbol = "ï£– " # TODO

[python]
symbol = "íƒ¼ "

[rlang]
symbol = "íƒ¿ "

[ruby]
symbol = "í„– "

[rust]
symbol = "í„— "

[scala]
symbol = "í„ "

[shell]
format = '[$indicator]($style)'
fish_indicator = ''
bash_indicator = 'bsh '
zsh_indicator = 'zsh '
disabled = false

[spack]
symbol = "ğŸ…¢ " # TODO

[swift]
symbol = 'í…€ '
disabled = true
